# Generated by Django 4.1 on 2022-10-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_rename_name_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
