# Generated by Django 4.1 on 2022-08-30 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amenities_Name', models.CharField(choices=[('D', 'Dishwasher'), ('F', 'Fireplace'), ('S', 'Swimming pool')], max_length=20)),
                ('Cration_Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Descriptions', models.CharField(max_length=300)),
                ('Type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=11)),
                ('Purpose_Type', models.CharField(choices=[('Unfurnised', 'Unfurnised'), ('semi-furnised', 'semi-furnised'), ('furnised', 'furnised')], max_length=13)),
                ('Bedrooms', models.IntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'three')], max_length=1)),
                ('Batrooms', models.IntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'three')], max_length=1)),
                ('Furnishing_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=11)),
                ('Property_Tenure', models.CharField(choices=[('Unfurnised', 'Unfurnised'), ('semi-furnised', 'semi-furnised'), ('furnised', 'furnised')], max_length=13)),
                ('size', models.CharField(max_length=300)),
                ('Build_up_Area', models.CharField(max_length=300)),
                ('parking_number', models.CharField(max_length=300)),
                ('Property_Developer', models.CharField(max_length=300)),
                ('Build_year', models.CharField(max_length=300)),
                ('Building_Floor', models.CharField(max_length=300)),
                ('Floor_number', models.CharField(max_length=300)),
                ('Dewa_number', models.CharField(max_length=300)),
                ('Occupancy', models.CharField(choices=[('Owner occupied', 'Owner occupied'), ('Investment', 'Investment'), ('Vacant', 'Vacant'), ('Tenanted', 'Tenanted')], max_length=14)),
                ('Project_status', models.CharField(choices=[('Off plane', 'Off plane'), ('completed', 'completed')], max_length=9)),
                ('Renovation_type', models.CharField(choices=[('Fully upgraded', 'Fully upgraded'), ('Partially upgraded', 'Partially upgraded')], max_length=18)),
                ('Layout_type', models.CharField(max_length=300)),
                ('property_pricing', models.CharField(max_length=300)),
                ('Service_charge', models.CharField(max_length=300)),
                ('financial_status', models.CharField(choices=[('Mortgaged', 'Mortgaged'), ('Cash', 'Cash')], max_length=9)),
                ('Cheques', models.IntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'three')], max_length=1)),
                ('property_location', models.CharField(max_length=300)),
                ('street_Address', models.CharField(max_length=300)),
                ('project_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_name', models.CharField(choices=[('A', 'Apartment'), ('B', 'Bungalow'), ('C', 'Compound'), ('D', 'Duplex'), ('F', 'Full floor'), ('H', 'Half floor'), ('L', 'Land'), ('P', 'Pent House'), ('T', 'Town House'), ('V', 'Villa'), ('W', 'Whole Building'), ('H', 'Hotel apartments'), ('U', 'Bulk units')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Listing_Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_path', models.ImageField(upload_to='uploads/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='listing.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Listing_Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cration_Time', models.DateTimeField(auto_now_add=True)),
                ('Amenities_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.amenities')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='Property_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.property_type'),
        ),
        migrations.AddField(
            model_name='listing',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amenities',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Amenities', to='listing.listing'),
        ),
    ]
