# Generated by Django 4.1 on 2022-09-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='property_Usage',
        ),
        migrations.AlterField(
            model_name='amenities',
            name='Amenities_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Furnishing_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=11),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Property_Tenure',
            field=models.CharField(choices=[('Single Family', 'Single Family'), ('Bachelors', 'Bachelors')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='listing_amenities',
            name='Amenities_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Amenities_ID', to='listing.amenities'),
        ),
        migrations.AlterField(
            model_name='listing_amenities',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Amenities', to='listing.listing'),
        ),
    ]
