# Generated by Django 3.2.15 on 2022-08-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_favouritelisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritelisting',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.listing'),
        ),
    ]
