# Generated by Django 4.1 on 2022-09-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_compress_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compress_image',
            old_name='photo',
            new_name='images_path',
        ),
    ]
