# Generated by Django 4.1 on 2022-09-24 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_listing_property_usage_alter_listing_furnishing_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing_amenities',
            name='Amenities_ID',
        ),
        migrations.AddField(
            model_name='listing',
            name='Amenities_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Amenities_ID', to='listing.amenities'),
        ),
    ]
