# Generated by Django 4.1 on 2022-09-25 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_remove_listing_amenities_amenities_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritelisting',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='favouritelisting',
            name='user',
        ),
        migrations.RemoveField(
            model_name='listingquestionair',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='listingquestionair',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userquestionair',
            name='question',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='Amenities_ID',
        ),
        migrations.AddField(
            model_name='listing_amenities',
            name='Amenities_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Amenities_ID', to='listing.amenities'),
        ),
        migrations.DeleteModel(
            name='BasicQuestionair',
        ),
        migrations.DeleteModel(
            name='FavouriteListing',
        ),
        migrations.DeleteModel(
            name='ListingQuestionair',
        ),
        migrations.DeleteModel(
            name='UserQuestionair',
        ),
    ]
