# Generated by Django 4.1 on 2022-10-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_remove_favouritelisting_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Project_status',
            field=models.CharField(choices=[('Off plan', 'Off plan'), ('Completed', 'Completed')], max_length=9),
        ),
    ]
