# Generated by Django 4.1 on 2022-10-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_alter_listing_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_favourite',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
