# Generated by Django 4.1 on 2022-10-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_listing_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_favourite',
        ),
    ]
