# Generated by Django 4.1 on 2022-10-11 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_alter_listing_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionair', '0002_questionanswer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_anwser', to='listing.listing'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answer', to='questionair.question'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ListingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_question', to='listing.listing')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='questionair.question')),
            ],
        ),
    ]
