# Generated by Django 4.1 on 2022-10-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionair', '0003_alter_questionanswer_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingquestion',
            name='expected_Answer',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
