# Generated by Django 4.1 on 2022-10-25 08:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0008_remove_listing_is_favourite'),
        ('questionair', '0005_interestedqanswer_delete_questionanswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='interestedqAnswer',
            new_name='interestedAnswer',
        ),
    ]
